name: Dockerfile-CI

on:
  push:
    branches: [ master, pull_request ]
  pull_request:
    branches: [ master, pull_request ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.0.1
        with:
          no-cache: true # optional, default is false
          github-token:  ${{ secrets.PACKAGE_ACTIONS_CI }} # optional, default is ${{ github.token }}
